services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErrorWatch\Symfony\Cache\TraceableCacheAdapter:
        decorates: 'cache.app'
        arguments:
            $decorated: '@.inner'
            $collector: '@ErrorWatch\Symfony\Service\TransactionCollector'
            $profile: '@?ErrorWatch\Symfony\Profiler\RequestProfile'
