services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErrorWatch\Symfony\EventSubscriber\MessengerSubscriber:
        arguments:
            $client: '@ErrorWatch\Sdk\Client'
            $captureRetries: '%error_watch.messenger.capture_retries%'
            $profile: '@?ErrorWatch\Symfony\Profiler\RequestProfile'
        tags:
            - { name: kernel.event_subscriber }

    ErrorWatch\Symfony\Messenger\TracingMiddleware:
        arguments:
            $collector: '@ErrorWatch\Symfony\Service\TransactionCollector'
            $sender: '@ErrorWatch\Symfony\Service\TransactionSender'
        tags:
            - { name: messenger.middleware }
